### ISSUE TITLE
唔大概需要优化一下

### ISSUE THREAD

**Issue by RugerMcCarthy** [compose-museum/jetpack-compose-tutorial#28]
![4E8719DC-45D6-4824-B3C6-26EF7B150CF5](https://user-images.githubusercontent.com/30253468/118157170-ce80e500-b44c-11eb-8cfe-43184ce94686.png)
移动端引用前端样式可能需要优化下，不妨加个scrollable？

**Comment by Nthily** [comment]
移动感觉可以不要内边距，但是我不会设置，麻了

**Comment by Nthily** [comment]
css 在这里 /docs/stylesheets/extra.css
