### ISSUE TITLE
code字体建议改成Jetbrains Mono增加阅读体验

### ISSUE THREAD

**Issue by RugerMcCarthy** [compose-museum/jetpack-compose-tutorial#34]
代码背景色可以考虑改成合适的暗色，更加醒些🥵

**Comment by Nthily** [comment]
背景色参考的安卓官方文档

**Comment by Nthily** [comment]
背景涩你看着调一下也可以

**Comment by RugerMcCarthy** [comment]
好捏，整张涩图捏

**Comment by Nthily** [comment]
不过我感觉似乎粗体还没有设置成功，以及代码大小可以改大一些，但是我不会力，我太菜了

**Comment by Nthily** [comment]
@RugerMcCarthy

**Comment by RugerMcCarthy** [comment]
CSS选择器对code标签设置字体样式不可以咩

**Comment by Nthily** [comment]
https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/

**Comment by Nthily** [comment]
可以，但是好像我前面下载到本地再导入好像 8 行

**Comment by Nthily** [comment]
俺试过好像 8 太行
