### ISSUE TITLE
什么是尾lambda

### ISSUE THREAD

**Issue by SMAXLYB** [compose-museum/jetpack-compose-tutorial#76]
在技术原理介绍重组原理那一篇文章中，有这一段话：

> 回到前面的例子，参数 text 作为表达式执行的调用处是 Button 的尾lambda，而后才作为参数传入 Text()。 所以此时最小重组范围是 Button 的 尾lambda 而非 Text()

这个尾lambda指的是哪块代码，代码中只有onClick{}和Text()调用了text表达式啊
```
@Composable
fun Foo() {
    var text by remember { mutableStateOf("文字") }
    Log.d("TAG", "Foo")
    Button(
        onClick = { text = "$text $text" }.also {
            Log.d("TAG", "Button")
        }
    ) {
        Log.d("TAG", "Button content lambda")
        Text(text).also {
            Log.d("TAG", "Text")
        }
    }
}
```

**Comment by Nthily** [comment]
感谢提交 issue！
![IMG_0480](https://user-images.githubusercontent.com/31311826/119320871-52707380-bc7c-11eb-8726-81823f79e4bc.png)
从 Button 的定义可以知道，最后一个参数 content 就是一个 lambda 表达式

**Comment by SMAXLYB** [comment]
kotlin的这个语法我懂了，我的疑问就在于text并没有在lambda中被单独使用，仅被Text()使用，最小范围怎么是lambda？我这样理解是不是对的：
text在Text()中被调用，而Text()在Button的lambda里面，所以text的也在Button的lambda里面，所以此时最小重组范围是 Button 的 lambda 而非 Text()

**Comment by RugerMcCarthy** [comment]
“text在Text()中被调用”这样理解是错误的，text作为参数传递给Text()，他的上下文仍然在当前Button尾部lambda作用域，所以最小重组范围是Button尾部lambda作用域

**Comment by SMAXLYB** [comment]
懂了，非常感谢两位！

**Comment by Nthily** [comment]
@SMAXLYB 关于这个作用域还有其他的一些细节问题，请参考[这里](https://github.com/compose-museum/jetpack-compose-tutorial/issues/101)
